resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers

    [managers:children]
    active

    [active]
    ${yandex_compute_instance.studywebserviceru.hostname} ansible_host=${yandex_compute_instance.studywebserviceru.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.studywebserviceru
  ]
}
